# Generated by Django 4.2.6 on 2023-10-29 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_level', models.PositiveIntegerField(default=1)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('published_articles', models.PositiveIntegerField(default=0)),
                ('rejected_articles', models.PositiveIntegerField(default=0)),
                ('author_status', models.CharField(choices=[('Active', 'Active'), ('Demoted', 'Demoted'), ('Expelled', 'Expelled')], default='Active', max_length=10)),
                ('payment_details', models.TextField(blank=True)),
                ('monetized_articles', models.PositiveIntegerField(default=0)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('coverimage', models.ImageField(upload_to='blog_covers/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.CharField(choices=[('Jobs', 'Jobs'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Health', 'Health'), ('Sports', 'Sports'), ('Relationship', 'Relationship'), ('Society', 'Society'), ('Fashion and Design', 'Fashion and Design'), ('Agriculture', 'Agriculture'), ('Business', 'Business'), ('Education', 'Education')], max_length=20)),
                ('link', models.URLField(default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaminiclone.authorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operaminiclone.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='operaminiclone.comment')),
            ],
        ),
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaminiclone.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
