# Generated by Django 4.2.6 on 2023-10-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaminiclone', '0002_blog_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
    ]
