# Generated by Django 4.2.6 on 2023-10-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaminiclone', '0003_remove_blog_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.CharField(default='error', max_length=150),
        ),
    ]
