# Generated by Django 4.2.6 on 2023-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaminiclone', '0007_alter_blog_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='reader',
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(blank=True, default=None, editable=False, max_length=150, null=True),
        ),
    ]
