# Generated by Django 4.2.6 on 2023-10-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaminiclone', '0008_rename_author_comment_reader_alter_blog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(max_length=240),
        ),
    ]
