# Generated by Django 4.2.6 on 2023-10-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaminiclone', '0014_alter_reply_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
    ]
